package model;
// Generated Jul 30, 2020 7:57:30 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conference generated by hbm2java
 */
public class Conference  implements java.io.Serializable {


     private Integer conferenceId;
     private Place place;
     private String conferenceName;
     private String summaryDescription;
     private String detailDescription;
     private Date dateStart;
     private Date dateEnd;
     private Set userjoinconferences = new HashSet(0);

    public Conference() {
    }

	
    public Conference(String conferenceName) {
        this.conferenceName = conferenceName;
    }
    public Conference(Place place, String conferenceName, String summaryDescription, String detailDescription, Date dateStart, Date dateEnd, Set userjoinconferences) {
       this.place = place;
       this.conferenceName = conferenceName;
       this.summaryDescription = summaryDescription;
       this.detailDescription = detailDescription;
       this.dateStart = dateStart;
       this.dateEnd = dateEnd;
       this.userjoinconferences = userjoinconferences;
    }
   
    public Integer getConferenceId() {
        return this.conferenceId;
    }
    
    public void setConferenceId(Integer conferenceId) {
        this.conferenceId = conferenceId;
    }
    public Place getPlace() {
        return this.place;
    }
    
    public void setPlace(Place place) {
        this.place = place;
    }
    public String getConferenceName() {
        return this.conferenceName;
    }
    
    public void setConferenceName(String conferenceName) {
        this.conferenceName = conferenceName;
    }
    public String getSummaryDescription() {
        return this.summaryDescription;
    }
    
    public void setSummaryDescription(String summaryDescription) {
        this.summaryDescription = summaryDescription;
    }
    public String getDetailDescription() {
        return this.detailDescription;
    }
    
    public void setDetailDescription(String detailDescription) {
        this.detailDescription = detailDescription;
    }
    public Date getDateStart() {
        return this.dateStart;
    }
    
    public void setDateStart(Date dateStart) {
        this.dateStart = dateStart;
    }
    public Date getDateEnd() {
        return this.dateEnd;
    }
    
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }
    public Set getUserjoinconferences() {
        return this.userjoinconferences;
    }
    
    public void setUserjoinconferences(Set userjoinconferences) {
        this.userjoinconferences = userjoinconferences;
    }




}


