package model;
// Generated Jul 30, 2020 7:57:30 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Place generated by hbm2java
 */
public class Place  implements java.io.Serializable {


     private Integer placeId;
     private String placeName;
     private String address;
     private Integer contained;
     private Set conferences = new HashSet(0);

    public Place() {
    }

	
    public Place(String placeName, String address) {
        this.placeName = placeName;
        this.address = address;
    }
    public Place(String placeName, String address, Integer contained, Set conferences) {
       this.placeName = placeName;
       this.address = address;
       this.contained = contained;
       this.conferences = conferences;
    }
   
    public Integer getPlaceId() {
        return this.placeId;
    }
    
    public void setPlaceId(Integer placeId) {
        this.placeId = placeId;
    }
    public String getPlaceName() {
        return this.placeName;
    }
    
    public void setPlaceName(String placeName) {
        this.placeName = placeName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getContained() {
        return this.contained;
    }
    
    public void setContained(Integer contained) {
        this.contained = contained;
    }
    public Set getConferences() {
        return this.conferences;
    }
    
    public void setConferences(Set conferences) {
        this.conferences = conferences;
    }




}


