package model;
// Generated Jul 30, 2020 7:57:30 AM by Hibernate Tools 4.3.1



/**
 * Userjoinconference generated by hbm2java
 */
public class Userjoinconference  implements java.io.Serializable {


     private UserjoinconferenceId id;
     private Conference conference;
     private User user;

    public Userjoinconference() {
    }

    public Userjoinconference(UserjoinconferenceId id, Conference conference, User user) {
       this.id = id;
       this.conference = conference;
       this.user = user;
    }
   
    public UserjoinconferenceId getId() {
        return this.id;
    }
    
    public void setId(UserjoinconferenceId id) {
        this.id = id;
    }
    public Conference getConference() {
        return this.conference;
    }
    
    public void setConference(Conference conference) {
        this.conference = conference;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


